### ISSUE TITLE
Building Error Caused by: failed to load source for a dependency on `termion` 

### ISSUE THREAD

**Issue by corvinux** [redox-os/termion#148]
Trying to build redox but I'm getting building error:
`Updating git repository `https://github.com/redox-os/termion.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `termion`

Caused by:
  Unable to update https://github.com/redox-os/termion.git#88cba89b

Caused by:
  revspec '88cba89b23f2b8a18c14a5ca7cd8024be8d6f04d' not found; class=Reference (4); code=NotFound (-3)
./repo.sh failed.mk/filesystem.mk:2: recipe for target 'build/filesystem.bin' failed
make: *** [build/filesystem.bin] Error 1

**Comment by malmrose** [comment]
This is my first time compiling this project, and I get this error too.

**Comment by JoshMcguigan** [comment]
What version of rustc and cargo are you using? Can you try running `cargo update` and trying again?

**Comment by alebcay** [comment]
Same situation as others above - first time compiling, getting this error. My `rustc` and `cargo` versions are `rustc 1.27.0-nightly (7f3444e1b 2018-04-26)` and `cargo 1.27.0-nightly (0a1add2d8 2018-04-20)`, respectively. Where in the source tree should I run `cargo update`?

**Comment by jackpot51** [comment]
Which repository is having this issue?

**Comment by alebcay** [comment]
I'm pretty sure it's happening when trying to build in [`installer`](https://github.com/redox-os/installer).

**Comment by jackpot51** [comment]
`cook - extrautils build`

Looks like extrautils. I will address it

**Comment by jackpot51** [comment]
Fixed in latest master of extrautils
