### ISSUE TITLE
Detect if terminal supports colors

### ISSUE THREAD

**Issue by gyscos** [redox-os/termion#78]
Ncurses has [`has_colors()`] to detect when a terminal doesn't support colors (like the linux TTY).
This can be used to trigger fallback mechanisms.

Having a similar method in termion would be nice.

[`has_colors()`]: https://github.com/gittup/ncurses/blob/gittup/ncurses/base/lib_color.c#L454

**Comment by ticki** [comment]
Definitely!

**Comment by IGI-111** [comment]
Terminfo lies about color support most of the time, but [this method](http://unix.stackexchange.com/questions/23763/checking-how-many-colors-my-terminal-emulator-supports) should work fine and let us both find out quickly if no color is supported by testing color 0 or find out the number of colors supported with a simple binary search.

It should also be properly documented that these kinds of capability checks are never authoritative. It's perfectly possible, if unlikely, for a terminal to support 256 colors yet not answer to `$'\e]4;0;?\a'`.

As for detecting true color support, there is no specified way but checking `$COLORTERM` is the most common way of doing it.
